### ISSUE TITLE
No changes are made in the Actions.c file

### ISSUE THREAD

**Issue by AhmedEJ** [Dynatrace/Dynatrace-LoadRunner-Request-Tagging#10]
Patching (tagging) a LoadRunner script completes without errors. However, the following happens: 

1. Header injection function is correctly added to globals.h file
2. No changes are made in the Actions.c file

This issue is possibly linked to [Compilation error due to undeclared identifier 'NULL' ](https://github.com/Dynatrace/Dynatrace-LoadRunner-Request-Tagging/issues/9) and missing libraries.

**Comment by dglugla** [comment]
no web requests posted, nor web_* methods called in sample code
