### ISSUE TITLE
String index out of bound exception, String index out of range 401

### ISSUE THREAD

**Issue by wa-spare** [Dynatrace/Dynatrace-LoadRunner-Request-Tagging#4]
Customer is running the tool and getting this error:  java.lang.StringIndexOutOfBoundsException: String 
index out of range: 401

Related Dynatrace SUP Ticket:  SUP-15251
![lrtaggingtool](https://user-images.githubusercontent.com/23265357/47301400-d194fb00-d5ec-11e8-917d-9934a6078a54.png)

**Comment by dglugla** [comment]
Hi @wa-spare 
Could you please share the file(s) that we can use to reproduce the issue?
Thanks, Darek

**Comment by 10621398** [comment]
[Supporting Files.zip](https://github.com/Dynatrace/Dynatrace-LoadRunner-Request-Tagging/files/2576869/Supporting.Files.zip)
@dglugla : All the supporting files is uploaded for  you to reproduce the issue.

Thanks,
Anand

**Comment by 10621398** [comment]
@dglugla : Did you got chance to reproduce the issue from your end?
Awaiting for your response.

Thanks,
Anand

**Comment by dglugla** [comment]
@10621398 : yes; fix is on the way, awaiting for approval

**Comment by dglugla** [comment]
fixed in latest release: https://github.com/Dynatrace/Dynatrace-LoadRunner-Request-Tagging/releases/tag/1.1.1
@10621398 please confirm

**Comment by 10621398** [comment]
@dglugla: Yes, its working. Thanks for your help.
I will execute the scripts once and will verify you.
